CREATE TABLE departure
(
    id                       VARCHAR(255) NOT NULL PRIMARY KEY,
    price                    FLOAT        NOT NULL,
    description              VARCHAR(255),
    total_window             INT,
    start_destination        INT,
    end_destination          INT,
    start_location           VARCHAR(255),
    end_location             VARCHAR(255),
    passenger_limit          INT,
    passenger_total          INT,
    payment_type_list        VARCHAR(255),
    facility_list            VARCHAR(255),
    start_hours_of_departure TIME,
    end_hours_of_departure   TIME,
    traveling_time_hours     INT,
    traveling_time_minute    INT,
    promo_id                 VARCHAR(255),
    company_id               VARCHAR(255),
    departure_status_id      INT,
    created                  TIMESTAMP    NOT NULL,
    updated                  TIMESTAMP,
    CONSTRAINT fk_departure_promo FOREIGN KEY (promo_id) REFERENCES promo (id),
    CONSTRAINT fk_departure_company FOREIGN KEY (company_id) REFERENCES company (id),
    CONSTRAINT fk_departure_company_start FOREIGN KEY (start_destination) REFERENCES destination (id),
    CONSTRAINT fk_departure_company_end FOREIGN KEY (end_destination) REFERENCES destination (id)
);